### ISSUE TITLE
ModuleNotFoundError: No module named 'pyaudioop'

### ISSUE THREAD

**Issue by FuriFull** [DrewThomasson/ebook2audiobookXTTS#42]
Hello, tried to run app.py and got this error:

```
c:\Audiobooks>python app.py
starting...
Traceback (most recent call last):
  File "c:\Audiobooks\pydub\utils.py", line 14, in <module>
    import audioop
ModuleNotFoundError: No module named 'audioop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Audiobooks\app.py", line 91, in <module>
    from pydub import AudioSegment
  File "c:\Audiobooks\pydub\__init__.py", line 1, in <module>
    from .audio_segment import AudioSegment
  File "c:\Audiobooks\pydub\audio_segment.py", line 11, in <module>
    from .utils import mediainfo_json, fsdecode
  File "c:\Audiobooks\pydub\utils.py", line 16, in <module>
    import pyaudioop as audioop
ModuleNotFoundError: No module named 'pyaudioop'
```

Tried python from 3.11 to 3.9 - results are the same

**Comment by ROBERT-MCDOWELL** [comment]
pip install pyaudioop

**Comment by DrewThomasson** [comment]
#### Have you tried doing 
```bash
pip install pydub --upgrade
```
### To see if that fixes it? 🤔

**Comment by FuriFull** [comment]
Now it's regex error

```
c:\Audiobooks>python app.py
starting...
Traceback (most recent call last):
  File "c:\Audiobooks\app.py", line 94, in <module>
    import nltk
  File "c:\Audiobooks\nltk\__init__.py", line 138, in <module>
    from nltk.text import *
  File "c:\Audiobooks\nltk\text.py", line 30, in <module>
    from nltk.tokenize import sent_tokenize
  File "c:\Audiobooks\nltk\tokenize\__init__.py", line 66, in <module>
    from nltk.tokenize.casual import TweetTokenizer, casual_tokenize
  File "c:\Audiobooks\nltk\tokenize\casual.py", line 49, in <module>
    import regex  # https://github.com/nltk/nltk/issues/2409
  File "c:\Audiobooks\regex\__init__.py", line 1, in <module>
    from .regex import *
  File "c:\Audiobooks\regex\regex.py", line 417, in <module>
    import regex._regex_core as _regex_core
  File "c:\Audiobooks\regex\_regex_core.py", line 21, in <module>
    import regex._regex as _regex
ModuleNotFoundError: No module named 'regex._regex'
```

**Comment by FuriFull** [comment]
Yeah, thx, docker is fine, works well.
